title: KAARNIKA A
logo: assets/images/Kaarnika.jpg
description: A results-driven data science graduate with experience in machine learning, medical diagnostics, and agricultural analysis. Skilled in Python, R, Power BI, and techniques like BERT, LSTM, and ARIMA. Published researcher in quantum computing and crop prediction, with strong communication and collaboration skills.
theme: jekyll-theme-minima
